# 📊 Análise de Dados Musicais - Spotify & YouTube

## 🎯 Contexto do Projeto

**Você foi contratado pela Mateus Music** como Cientista de Dados para analisar o catálogo musical da empresa. Sua missão é explorar a base de dados contendo **mais de 20.000 músicas** e extrair insights valiosos sobre o desempenho dos artistas nas plataformas Spotify e YouTube.

A empresa precisa entender:
- Quem são os artistas mais relevantes
- Quais músicas performam melhor
- Como otimizar investimentos em marketing digital

## 📁 Sobre a Base de Dados

### Características Principais:
- **+20.000 músicas** no catálogo completo
- Dados de **Streams no Spotify** 
- Dados de **Views no YouTube**
- **Links dos vídeos** do YouTube para cada música
- **Metadados completos** de artistas e faixas

### 1. Importe o Pandas e mostre as informações gerais do dataframe

In [1]:
import pandas as pd

In [2]:
df= pd.read_parquet('Dados_Artistas.parquet')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20718 entries, 0 to 20717
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Artist            20718 non-null  str
 1   Url_spotify       20718 non-null  str
 2   Track             20718 non-null  str
 3   Album             20718 non-null  str
 4   Album_type        20718 non-null  str
 5   Uri               20718 non-null  str
 6   Danceability      20716 non-null  float64
 7   Energy            20716 non-null  float64
 8   Key               20716 non-null  float64
 9   Loudness          20716 non-null  float64
 10  Speechiness       20716 non-null  float64
 11  Acousticness      20716 non-null  float64
 12  Instrumentalness  20716 non-null  float64
 13  Liveness          20716 non-null  float64
 14  Valence           20716 non-null  float64
 15  Tempo             20716 non-null  float64
 16  Duration_ms       20716 non-null  float64
 17  Url_youtube       20248 non-null  str
 18  Title             20248 non-null  str
 19  Channel           20248 non-null  str
 20  Views             20248 non-null  float64
 21  Likes             20177 non-null  float64
 22  Comments          20149 non-null  float64
 23  Description       19842 non-null  str
 24  Licensed          20248 non-null  object
 25  official_video    20248 non-null  object
 26  Stream            20142 non-null  float64
dtypes: float64(15), object(2), str(10)
memory usage: 31.0+ MB

### 2. Mostre as cinco primeiras linhas do dataframe

In [3]:
df.head()

,Artist,Url_spotify,Track,Album,Album_type,Uri,Danceability,Energy,Key,Loudness,...,Url_youtube,Title,Channel,Views,Likes,Comments,Description,Licensed,official_video,Stream
0,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Feel Good Inc.,Demon Days,album,spotify:track:0d28khcov6AiegSCpG5TuT,0.818,0.705,6.0,-6.679,...,https://www.youtube.com/watch?v=HyHNuVaZJ-k,Gorillaz - Feel Good Inc. (Official Video),Gorillaz,693555221.0,6220896.0,169907.0,Official HD Video for Gorillaz' fantastic trac...,True,True,1.040235e+09
1,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Rhinestone Eyes,Plastic Beach,album,spotify:track:1foMv2HQwfQ2vntFf9HFeG,0.676,0.703,8.0,-5.815,...,https://www.youtube.com/watch?v=yYDmaexVHic,Gorillaz - Rhinestone Eyes [Storyboard Film] (...,Gorillaz,72011645.0,1079128.0,31003.0,The official video for Gorillaz - Rhinestone E...,True,True,3.100837e+08
2,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,New Gold (feat. Tame Impala and Bootie Brown),New Gold (feat. Tame Impala and Bootie Brown),single,spotify:track:64dLd6rVqDLtkXFYrEUHIU,0.695,0.923,1.0,-3.930,...,https://www.youtube.com/watch?v=qJa-VFwPpYA,Gorillaz - New Gold ft. Tame Impala & Bootie B...,Gorillaz,8435055.0,282142.0,7399.0,Gorillaz - New Gold ft. Tame Impala & Bootie B...,True,True,6.306347e+07
3,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,On Melancholy Hill,Plastic Beach,album,spotify:track:0q6LuUqGLUiCPP1cbdwFs3,0.689,0.739,2.0,-5.810,...,https://www.youtube.com/watch?v=04mfKJWDSzI,Gorillaz - On Melancholy Hill (Official Video),Gorillaz,211754952.0,1788577.0,55229.0,Follow Gorillaz online:\nhttp://gorillaz.com \...,True,True,4.346636e+08
4,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Clint Eastwood,Gorillaz,album,spotify:track:7yMiX7n9SBvadzox8T5jzT,0.663,0.694,10.0,-8.627,...,https://www.youtube.com/watch?v=1V_xRb0x9aw,Gorillaz - Clint Eastwood (Official Video),Gorillaz,618480958.0,6197318.0,155930.0,The official music video for Gorillaz - Clint ...,True,True,6.172597e+08

### 3. Vamos ver quais os artistas temos em nosso df e contar quantos artistas diferentes temos no nosso dataset

In [4]:
df['Artist']
df['Artist'].value_counts()

Artist
Gorillaz                 10
Red Hot Chili Peppers    10
50 Cent                  10
Metallica                10
Coldplay                 10
                         ..
Shubh                     6
NewJeans                  6
Jimin                     3
Bootie Brown              1
Stars Music Chile         1
Name: count, Length: 2079, dtype: int64

### 4. Quais os 10 artistas com mais musicas em nosso dataset?

In [5]:
### vamos verifcar os artistas com mais musicas na lista
df['Artist'].value_counts().head(10)

Artist
Gorillaz                 10
Red Hot Chili Peppers    10
50 Cent                  10
Metallica                10
Coldplay                 10
Daft Punk                10
Linkin Park              10
Radiohead                10
AC/DC                    10
Black Eyed Peas          10
Name: count, dtype: int64

### 5. Quais as 5 músicas com musicas com mais views no youtube?

In [6]:
### quero mostrar as 5 musicas com mais views no youtube
df

,Artist,Url_spotify,Track,Album,Album_type,Uri,Danceability,Energy,Key,Loudness,...,Url_youtube,Title,Channel,Views,Likes,Comments,Description,Licensed,official_video,Stream
0,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Feel Good Inc.,Demon Days,album,spotify:track:0d28khcov6AiegSCpG5TuT,0.818,0.705,6.0,-6.679,...,https://www.youtube.com/watch?v=HyHNuVaZJ-k,Gorillaz - Feel Good Inc. (Official Video),Gorillaz,693555221.0,6220896.0,169907.0,Official HD Video for Gorillaz' fantastic trac...,True,True,1.040235e+09
1,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Rhinestone Eyes,Plastic Beach,album,spotify:track:1foMv2HQwfQ2vntFf9HFeG,0.676,0.703,8.0,-5.815,...,https://www.youtube.com/watch?v=yYDmaexVHic,Gorillaz - Rhinestone Eyes [Storyboard Film] (...,Gorillaz,72011645.0,1079128.0,31003.0,The official video for Gorillaz - Rhinestone E...,True,True,3.100837e+08
2,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,New Gold (feat. Tame Impala and Bootie Brown),New Gold (feat. Tame Impala and Bootie Brown),single,spotify:track:64dLd6rVqDLtkXFYrEUHIU,0.695,0.923,1.0,-3.930,...,https://www.youtube.com/watch?v=qJa-VFwPpYA,Gorillaz - New Gold ft. Tame Impala & Bootie B...,Gorillaz,8435055.0,282142.0,7399.0,Gorillaz - New Gold ft. Tame Impala & Bootie B...,True,True,6.306347e+07
3,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,On Melancholy Hill,Plastic Beach,album,spotify:track:0q6LuUqGLUiCPP1cbdwFs3,0.689,0.739,2.0,-5.810,...,https://www.youtube.com/watch?v=04mfKJWDSzI,Gorillaz - On Melancholy Hill (Official Video),Gorillaz,211754952.0,1788577.0,55229.0,Follow Gorillaz online:\nhttp://gorillaz.com \...,True,True,4.346636e+08
4,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Clint Eastwood,Gorillaz,album,spotify:track:7yMiX7n9SBvadzox8T5jzT,0.663,0.694,10.0,-8.627,...,https://www.youtube.com/watch?v=1V_xRb0x9aw,Gorillaz - Clint Eastwood (Official Video),Gorillaz,618480958.0,6197318.0,155930.0,The official music video for Gorillaz - Clint ...,True,True,6.172597e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20713,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,JUST DANCE HARDSTYLE,JUST DANCE HARDSTYLE,single,spotify:track:0RtcKQGyI4hr8FgFH1TuYG,0.582,0.926,5.0,-6.344,...,https://www.youtube.com/watch?v=5SHmKFKlNqI,JUST DANCE HARDSTYLE,SICK LEGEND - Topic,71678.0,1113.0,0.0,Provided to YouTube by Routenote\n\nJUST DANCE...,True,True,9.227144e+06
20714,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,SET FIRE TO THE RAIN HARDSTYLE,SET FIRE TO THE RAIN HARDSTYLE,single,spotify:track:3rHvPA8lUnPBkaLyPOc0VV,0.531,0.936,4.0,-1.786,...,https://www.youtube.com/watch?v=ocTH6KxllDQ,SET FIRE TO THE RAIN HARDSTYLE,SICK LEGEND - Topic,164741.0,2019.0,0.0,Provided to YouTube by Routenote\n\nSET FIRE T...,True,True,1.089818e+07
20715,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,OUTSIDE HARDSTYLE SPED UP,OUTSIDE HARDSTYLE SPED UP,single,spotify:track:4jk00YxPtPbhvHJE9N4ddv,0.443,0.830,4.0,-4.679,...,https://www.youtube.com/watch?v=5wFhE-HY0hg,OUTSIDE HARDSTYLE SPED UP,SICK LEGEND - Topic,35646.0,329.0,0.0,Provided to YouTube by Routenote\n\nOUTSIDE HA...,True,True,6.226110e+06
20716,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,ONLY GIRL HARDSTYLE,ONLY GIRL HARDSTYLE,single,spotify:track:5EyErbpsugWliX006eTDex,0.417,0.767,9.0,-4.004,...,https://www.youtube.com/watch?v=VMFLbFRNCn0,ONLY GIRL HARDSTYLE,SICK LEGEND - Topic,6533.0,88.0,0.0,Provided to YouTube by Routenote\n\nONLY GIRL ...,True,True,6.873961e+06
20717,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,MISS YOU HARDSTYLE,MISS YOU HARDSTYLE,single,spotify:track:6lOn0jz1QpjcWeXo1oMm0k,0.498,0.938,6.0,-4.543,...,https://www.youtube.com/watch?v=zau0dckCFi0,MISS YOU HARDSTYLE,SICK LEGEND - Topic,158697.0,2484.0,0.0,Provided to YouTube by Routenote\n\nMISS YOU H...,True,True,5.695584e+06

### 6. Quais os 5 artistas com mais streams no spotify?

In [7]:
### Quais os 5 artistas com mais streams no spotify?
df.sort_values(by='Stream',ascending=False).head()

,Artist,Url_spotify,Track,Album,Album_type,Uri,Danceability,Energy,Key,Loudness,...,Url_youtube,Title,Channel,Views,Likes,Comments,Description,Licensed,official_video,Stream
15250,The Weeknd,https://open.spotify.com/artist/1Xyo4u8uXC1ZmM...,Blinding Lights,After Hours,album,spotify:track:0VjIjW4GlUZAMYd2vXMi3b,0.514,0.730,1.0,-5.934,...,https://www.youtube.com/watch?v=4NRXx6U8ABQ,The Weeknd - Blinding Lights (Official Video),TheWeekndVEVO,6.741645e+08,8817927.0,282589.0,"Official music video for The Weeknd ""Blinding ...",True,True,3.386520e+09
12452,Ed Sheeran,https://open.spotify.com/artist/6eUKZXaKkcviH0...,Shape of You,÷ (Deluxe),album,spotify:track:7qiZfU4dY1lWllzX7mPBI3,0.825,0.652,1.0,-3.183,...,https://www.youtube.com/watch?v=JGwWNGJdvx8,Ed Sheeran - Shape of You (Official Music Video),Ed Sheeran,5.908398e+09,31047780.0,1130327.0,The official music video for Ed Sheeran - Shap...,True,True,3.362005e+09
19186,Lewis Capaldi,https://open.spotify.com/artist/4GNC7GD6oZMSxP...,Someone You Loved,Divinely Uninspired To A Hellish Extent,album,spotify:track:7qEHsqek33rTcFNT9PFqLf,0.501,0.405,1.0,-5.679,...,https://www.youtube.com/watch?v=zABLecsR5UE,Lewis Capaldi - Someone You Loved,LewisCapaldiVEVO,5.867684e+08,7367091.0,147565.0,Listen to my new single ‘Pointless’ here!\nhtt...,True,True,2.634013e+09
17937,Post Malone,https://open.spotify.com/artist/246dkjvS1zLTti...,rockstar (feat. 21 Savage),beerbongs & bentleys,album,spotify:track:0e7ipj03S05BNilyu5bRzt,0.585,0.520,5.0,-6.136,...,https://www.youtube.com/watch?v=UceaB4D0jpo,Post Malone ft. 21 Savage - rockstar (Official...,PostMaloneVEVO,1.060220e+09,12564657.0,366520.0,rockstar ft. 21 Savage (Official Video)\nSong ...,True,True,2.594927e+09
17938,Post Malone,https://open.spotify.com/artist/246dkjvS1zLTti...,Sunflower - Spider-Man: Into the Spider-Verse,Hollywood's Bleeding,album,spotify:track:0RiRZpuVRbi7oqRdSMwhQY,0.755,0.522,2.0,-4.368,...,https://www.youtube.com/watch?v=ApXoWvfEYVU,"Post Malone, Swae Lee - Sunflower (Spider-Man:...",PostMaloneVEVO,1.977389e+09,13749813.0,331063.0,Own Spider-Man: Into the Spider-verse on Digit...,True,True,2.538330e+09

### 7. Vamos converter e salvar o arquivo com parquet, para subir no github

In [ ]:
### vamos converter o arquivo para parquet
df.to_parquet('Dados_Artistas.parquet', index=False)